name: Sync branches

on:
 push:
   branches:
     - master

jobs:
 sync:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Sync branches
       run: |
         rm -rf homologacao  # Remove o diretório homologacao, se existir
         git clone --branch master --single-branch $CI_REPOSITORY_URL .  # Clona o repositório da master
         git checkout -b homologacao  # Cria e muda para a branch homologacao
         git push --set-upstream origin homologacao  # Empurra a nova branch de homologacao
